# Generated by Django 5.0.3 on 2024-04-09 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeid',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='placeid',
            name='longitude',
        ),
    ]
