# Generated by Django 5.0.3 on 2024-04-09 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_placeid_latitude_remove_placeid_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='place_identifier',
            new_name='place_id',
        ),
    ]
