# Generated by Django 4.2.11 on 2024-04-17 12:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_name_customer_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_identifier', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='place_id',
        ),
        migrations.DeleteModel(
            name='PlaceId',
        ),
        migrations.AddField(
            model_name='customer',
            name='parcel',
            field=models.ForeignKey(default="1", on_delete=django.db.models.deletion.CASCADE, to='customers.parcel'),
            preserve_default=False,
        ),
    ]
