# Generated by Django 4.2.11 on 2024-04-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_rename_parcel_identifier_parcel_partcel_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='partcel_identifier',
            new_name='parcel_identifier',
        ),
    ]
