# Generated by Django 4.2.11 on 2024-04-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_rename_partcel_identifier_parcel_parcel_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('campground_image', models.ImageField(upload_to='campgrounds/')),
            ],
        ),
        migrations.AddField(
            model_name='parcel',
            name='campground',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='customers.campground'),
            preserve_default=False,
        ),
    ]
